version: '3.5'

services:
  postgresql:
    image: postgres:15.4-alpine3.18
    restart: always
    container_name: postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - ./server/pgdata:/var/lib/postgresql/data
    env_file:
      - ./server/.env
    expose:
      - 5432 

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - postgresql
    volumes:
      - ./server/src:/server/src
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
    - "5173:5173"

volumes:
  pgdata: