version: '3.5'

services:
  postgresql:
    image: postgres:15.4-alpine3.18
    restart: always
    container_name: postgresql
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - postgresql
    volumes:
      - ./src:/server/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - postgresql
volumes:
  pgdata:
